apiVersion: v1
kind: ConfigMap
data:
  torrc: |-
    ORPort  198.23.146.220:9001 IPv4Only
    ExitRelay 0
    Nickname riceahap
    DataDirectory /var/lib/tor
    AccountingRule sum
    AccountingStart month 1 00:00
    AccountingMax 6000 GBytes
metadata:
  name: tor-configmap
  namespace: tor-relay
