apiVersion:  v1
kind: Service
metadata:
  name: tor-relay-svc
  namespace: tor-relay
spec:
  selector:
    app: tor-relay
  ports:
  - protocol: TCP
    port: 9002
    targetPort: 9002
  type: LoadBalancer
