---
apiVersion: v1
kind: Namespace
metadata:
  name: soft-serve
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soft-serve-pvc
  namespace: soft-serve
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: soft-serve-svc
  namespace: soft-serve
spec:
  selector:
    app: soft-serve
  ports:
    - protocol: TCP
      port: 22
      targetPort: 23231
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soft-serve
  namespace: soft-serve
spec:
  selector:
    matchLabels:
      app: soft-serve
  replicas: 1
  template:
    metadata:
      labels:
        app: soft-serve
    spec:
      containers:
        - name: soft-serve
          image: charmcli/soft-serve:v0.7.6
          imagePullPolicy: Always
          ports:
            - containerPort: 23231
          volumeMounts:
            - name: soft-serve-data
              mountPath: /soft-serve
          env:
            - name: SOFT_SERVE_INITIAL_ADMIN_KEYS
              value: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHM4Zr0PFN7QdOG2aJ+nuzRCK6caulrpY6bphA1Ppl8Y e@t14"
      volumes:
        - name: soft-serve-data
          persistentVolumeClaim:
            claimName: soft-serve-pvc
