---
- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes
  when: ansible_all_ipv6_addresses

- name: Partition extra drive
  parted:
    device: /dev/sdb
    number: 1
    flags: [lvm]
    state: present

- name: Create filesystem
  fstype: btrfs
  dev: /dev/sdb1

- name: Mount drive
  mount:
    fstype: btrfs
    src: /dev/sdb1
    path: /longhorn
    opts: rw
    state: mounted
