---
- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Update repositories and install wireguard-tools
  ansible.builtin.apt:
    name: wireguard-tools
    state: present
    update_cache: yes

- name: Setup alternate SSH port
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port 22"
  notify: "Restart sshd"
