---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zalando-postgres
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: default
  releaseName: zalando-postgres
  chart:
    spec:
      chart: postgres-operator
      sourceRef:
        kind: HelmRepository
        name: zalando-postgres
        namespace: flux-system
      interval: 1m
  values:
    controller:
      replicaCount: 1
