---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: minecraft-restic-backup
  namespace: minecraft
spec:
  concurrencyPolicy: Forbid
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: restic-forget
              image: restic/restic:latest
              workingDir: /data
              args:
                - forget
                - --prune
                - --keep-daily
                - "14"
                - --keep-monthly
                - "6"
              env:
                - name: RESTIC_REPOSITORY
                  valueFrom:
                    secretKeyRef:
                      name: minecraft-restic-secrets
                      key: bucketName
                      optional: false
                - name: RESTIC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: minecraft-restic-secrets
                      key: resticKey
                      optional: false
                - name: B2_ACCOUNT_ID
                  valueFrom:
                    secretKeyRef:
                      name: minecraft-restic-secrets
                      key: keyID
                      optional: false
                - name: B2_ACCOUNT_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minecraft-restic-secrets
                      key: applicationKey
                      optional: false
              volumeMounts:
                - name: backupdata
                  mountPath: /data
                  readOnly: true
          initContainers:
            - name: restic
              image: restic/restic:latest
              workingDir: /data
              args:
                - backup
                - --host
                - k8s
                - .
              env:
                - name: RESTIC_REPOSITORY
                  valueFrom:
                    secretKeyRef:
                      name: minecraft-restic-secrets
                      key: bucketName
                      optional: false
                - name: RESTIC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: minecraft-restic-secrets
                      key: resticKey
                      optional: false
                - name: B2_ACCOUNT_ID
                  valueFrom:
                    secretKeyRef:
                      name: minecraft-restic-secrets
                      key: keyID
                      optional: false
                - name: B2_ACCOUNT_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minecraft-restic-secrets
                      key: applicationKey
                      optional: false
              volumeMounts:
                - name: backupdata
                  mountPath: /data
                  readOnly: true
          volumes:
            - name: backupdata
              persistentVolumeClaim:
                claimName: mc-world
          restartPolicy: OnFailure
