apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: iofq-tls-cert
  namespace: iofq-web
spec:
  secretName: iofq-web-tls
  issuerRef:
    name: iofq-cloudflare-issuer
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  dnsNames:
  - "10110110.xyz"
  - "*.10110110.xyz"
