---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: iofq-web
  namespace: flux-system
spec:
  image: ghcr.io/iofq/iofq.net
  interval: 5m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: iofq-web
  namespace: flux-system
spec:
  filterTags:
    pattern: '[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  imageRepositoryRef:
    name: iofq-web
  policy:
    numerical:
      order: asc

