apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soft-serve-pvc
  namespace: soft-serve
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
