apiVersion:  v1
kind: Service
metadata:
  name: soft-serve-svc
  namespace: soft-serve
spec:
  selector:
    app: soft-serve
  ports:
  - protocol: TCP
    port: 2323
    targetPort: 23231
  type: LoadBalancer
