---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: iofq-web
  namespace: flux-system
spec:
  image: ghcr.io/iofq/iofq.net
  interval: 5m0s

