apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tor-relay-pvc
  namespace: tor-relay
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
