apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--certificatesresolvers.le-skovati.acme.email=YOUR_EMAIL@example.com"
      - "--certificatesresolvers.le-skovati.acme.storage=/data/acme.json"
      - "--certificatesresolvers.le-skovati.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.le-skovati.acme.dnschallenge=true"
      - "--certificatesResolvers.le-skovati.acme.dnschallenge.provider=cloudflare"
      - "--api.insecure=true"
      - "--accesslog=true"
      - "--log.level=INFO"
    env:
      - name: CF_DNS_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-skovati
            key: dns-token
