apiVersion: apps/v1
kind: Deployment
metadata:
  name: skovati-startpage-deploy
  namespace: skovati-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skovati-startpage
  template:
    metadata:
      labels:
        app: skovati-startpage
    spec:
      containers:
      - name: skovati-startpage
        image: ghcr.io/skovati/startpage:767662a-1669779074 # {"$imagepolicy": "flux-system:skovati-startpage-image-policy"}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
