---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: skovati-startpage-image-repo
  namespace: flux-system
spec:
  image: ghcr.io/skovati/startpage
  interval: 1m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: skovati-startpage-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: skovati-startpage-image-repo
  filterTags:
    pattern: '[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
