---
- name: Install fail2ban
  apt:
    pkg: fail2ban
    state: present

- name: Install ufw
  apt:
    pkg: ufw
    state: present

- name: Disable oracle cloud iptables rejects
  ansible.builtin.lineinfile:
    path: /etc/iptables/rules.v4
    regexp: "^-A INPUT -j REJECT --reject-with icmp-host-prohibited"
    line: "#^-A INPUT -j REJECT --reject-with icmp-host-prohibited"

- name: Disable oracle cloud iptables rejects
  ansible.builtin.lineinfile:
    path: /etc/iptables/rules.v4
    regexp: "^-A FORWARD -j REJECT --reject-with icmp-host-prohibited"
    line: "#^-A FORWARD -j REJECT --reject-with icmp-host-prohibited"

- name: Reload iptables rules
  ansible.builtin.shell:
    cmd: iptables-restore < /etc/iptables/rules.v4

- name: Disable ufw so we can configure it
  community.general.ufw:
    state: disabled
    policy: deny

- name: Disable ufw logging
  community.general.ufw:
    logging: "off"

- name: Disable ipv6
  ansible.builtin.lineinfile:
    path: /etc/default/ufw
    regexp: "^IPV6="
    line: IPV6=no

- name: Disable ufw (IPV6 prevents it from starting)
  community.general.ufw:
    state: disabled
    policy: deny

- name: Enable ufw
  community.general.ufw:
    state: enabled
    policy: deny

- name: Allow all in traffic over wg
  community.general.ufw:
    rule: allow
    interface: kilo0
    direction: in

- name: Allow all out traffic over wg
  community.general.ufw:
    rule: allow
    interface: kilo0
    direction: out

- name: Allow all in traffic over kube
  community.general.ufw:
    rule: allow
    interface: kube-bridge
    direction: in

- name: Allow all out traffic over kube
  community.general.ufw:
    rule: allow
    interface: kube-bridge
    direction: out

- name: Allow wireguard port
  community.general.ufw:
    rule: allow
    port: 51820

- name: Allow minecraft port
  community.general.ufw:
    rule: allow
    port: 25565

- name: Allow alt ssh port
  community.general.ufw:
    rule: allow
    port: 2022

- name: Allow OpenSSH traffic
  community.general.ufw:
    rule: allow
    port: ssh

- name: Reload ufw
  community.general.ufw:
    state: reloaded
