---
- name: Install fail2ban
  apt:
    pkg: fail2ban
    state: present

- name: Install ufw
  apt:
    pkg: ufw
    state: present

- name: Disable ufw logging
  community.general.ufw:
    logging: "off"

- name: Disable ipv6
  ansible.builtin.lineinfile:
    path: /etc/default/ufw
    regexp: "^IPV6="
    line: IPV6=no

- name: Disable ufw (IPV6 prevents it from starting)
  community.general.ufw:
    state: disabled
    policy: deny

- name: Enable ufw
  community.general.ufw:
    state: enabled
    policy: deny

- name: Allow all in traffic over wg
  community.general.ufw:
    rule: allow
    interface: kilo0
    direction: in

- name: Allow all out traffic over wg
  community.general.ufw:
    rule: allow
    interface: kilo0
    direction: out

- name: Allow all in traffic over kube
  community.general.ufw:
    rule: allow
    interface: kube-bridge
    direction: in

- name: Allow all out traffic over kube
  community.general.ufw:
    rule: allow
    interface: kube-bridge
    direction: out

- name: Allow wireguard port
  community.general.ufw:
    rule: allow
    port: 51820

- name: Allow minecraft port
  community.general.ufw:
    rule: allow
    port: 25565

- name: Allow alt ssh port
  community.general.ufw:
    rule: allow
    port: 2022

- name: Allow OpenSSH traffic
  community.general.ufw:
    rule: allow
    port: ssh

- name: Reload ufw
  community.general.ufw:
    state: reloaded
