---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: skovati-dev-image-policy
  namespace: flux-system
spec:
  filterTags:
    extract: $ts
    pattern: '[a-f0-9]+-(?P<ts>[0-9]+)'
  imageRepositoryRef:
    name: skovati-dev-image-repo
  policy:
    numerical:
      order: asc

