---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: skovati-startpage-image-repo
  namespace: flux-system
spec:
  image: ghcr.io/skovati/startpage
  interval: 1m0s

