apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- image-policy/image-automation.yaml
- image-policy/image-policy-iofq.yaml
- image-policy/image-policy-skovati-dev.yaml
- image-policy/image-policy-skovati-startpage.yaml
- install
- kustomization/kustomization-lab-xyz.yaml
- kustomization/kustomization-sops-secrets.yaml
- repos/repo-git-lab-xyz.yaml
- repos/repo-helm-nginx
- repos/repo-iofq-web.yaml
- repos/repo-skovati-dev.yaml
- repos/repo-skovati-startpage.yaml
