apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: skovati-cloudflare-issuer
  namespace: skovati-dev
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: acme@skovati.dev
    privateKeySecretRef:
      name: skovati-letsencrypt
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-skovati
            key: dns-token
