apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: skovati-dev-tls-cert
  namespace: skovati-dev
spec:
  secretName: skovati-dev-tls
  issuerRef:
    name: skovati-cf-issuer-prod
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  dnsNames:
  - "skovati.dev"
  - "*.skovati.dev"
  - "*.lab.skovati.dev"
