---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skovati-ingress
  namespace: skovati-dev
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - skovati.dev
    - start.skovati.dev
    secretName: skovati-dev-tls
  rules:
    - host: skovati.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skovati-svc
                port:
                  number: 80
    - host: start.skovati.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skovati-startpage-svc
                port:
                  number: 80
