apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: skovati-dev-tls-cert
  namespace: skovati-dev
spec:
  secretName: skovati-dev-tls
  issuerRef:
    name: skovati-cf-issuer-staging
    kind: ClusterIssuer
  privateKey:
    algorithm: Ed25519
  dnsNames:
  - "skovati.dev"
  - "*.skovati.dev"
