name: terraform

on:
  push:
    branches:
      - master
      - terraform
  pull_request:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      include:
        - environment: 182
          tf_backend: TF_BACKEND_182
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Run terraform init
        run: terraform init --backend-config="address=${{ secrets.[matrix.tf_backend] }}"
