name: Terraform Plan

on:
  push:
    branches:
      - **
    pull_request:
      - **
jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ['10110110']
    defaults:
      run:
        working-directory: ./terraform
    env:
      TF_WORKSPACE: ${{ matrix.workspace }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/terraform'
        run: terraform apply
