apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:2kHcX+G9Oh3YF8jnPXSSM4ZmpMxCn51n5bRa9cxEr+zHogXY4c+7SJ/99wh4y8fr5S1KrLFmvXE=,iv:I/oXuebcPZ4iau9PI4aAEfk35/1XQKd2LY+JXhxLwrY=,tag:O5HqX/02x8JMeFWpz8KjLw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: iofq-cloudflare-api
    namespace: iofq
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-28T01:27:15Z"
    mac: ENC[AES256_GCM,data:A/+sdLERxZQ9hXv1A9uAcgRUAcLONWxSy19yXJ+b6Uk17erPeu4AY+mnTNFEfvNdetmTVD3/jx7ZZ3ldht6UEMGv73+8tB2QhXBx187Z48qDhlsX0IckiEvN4BKhN9tDJI9N2M1p7v8MnctKzBd/2V9/WZhrslz6qg/JPM7KhkM=,iv:/I7NC69UorwEkYSGrx5ocRqz0uuwnRlNhhQTD4eljeE=,tag:JQyixEovwPEHTaA+g2N+IA==,type:str]
    pgp:
        - created_at: "2022-11-28T01:27:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/ACAxq+nVF6ARAAgNCH2EwZypF1GVTHGAzT8ECPwCKSUzZEjPg2gENs2QUd
            xUhCRJOjhiT0otaNqz4jiIjz59hCjpJI1W65VlU/NvE7/ZIUpMPltugL4BZGMc7X
            ipZZvVtoJ7msqRqVWzkqoFSJq+2VHrFl7Ed6ZiM3xmLJvtGy2y341sKz2WCkhXO/
            XM3zTrbwJvmulQJPb79foFb/Z2/gNBfnKrAPXbdrNU/JBYejvyDscKScFkRL8S85
            7SQOOcLL1AnoSfOhojem2VwAKH3bHjMbg18FPMN1SDC+ZF56XP46KsyQEKbw/Pls
            6BLRzYSwOqAc+7nnrGTOERcngztzzXLOtyM9PVF7+hfyTDPnfjDGeTGjHryyqefp
            ZzqfZ5+MBQXTQLwpKmzAa8Sz9/SkwlfjtN9wpPXDTkuShVU8dV2RzeWJZB7Dwvio
            gXokoAEqqzrsupKrvUYNH1KB0lAB7JyPryI8DvWq70HEONNQQEW1Wtqa8oIx1OxO
            lb66+VTs6/XAQZBDYJDESi/boPEAB+lZVu/YD6OjX9GXjsObYGsgFcHlyO3dJdMm
            XXgRCCL/1XpXNrPoEHS5vDx3SSszMM5tGvNX0zau3mmJ/UlAqfR/2yOYDY5RHz0u
            Bj59a3Y2yIgsrDjkdEXBMTM4ZZfxa+a5o3M5+wff9SwP+G3IzkQ3vmZ+nAGfNWnS
            XgGGQeNpOS4jWyc37610QlNipuy0Eb0yWgiS4rGi4OK9Q4XoQYKH/Ra7gIqnUzgn
            QI5BoCjUvwGMsjRgf2PHs2xiBHB4WSMX4fmgbknznIszzwZxjZ41F3rG1a01MkA=
            =Si2W
            -----END PGP MESSAGE-----
          fp: 7A5058C3DC616AB848AEC585F7A4B3A5DA36606A
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
