apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:gcokjJeubz/pVzqXRFatSUmj4aLYWPM6VJ/+cunoHDQRuSia33Fwhy9OPGLxLkBy1YoOzVuKkJ0=,iv:BgucAgsnBncpYaPl7hPaYDWB/MjJYckMDM8mmC3M6wM=,tag:mQ7+r6Opq6hZt8fArKUkDg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: skovati-cf-token-secret
    namespace: cert-manager
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-28T21:59:37Z"
    mac: ENC[AES256_GCM,data:wNLRa//Solmt2sRHzhd2LNVCSm/fNBvBj3qeoQmx3LYtSQv3sKeX7rYECN3cbdPxl9/L/51c6iV+focSpCET7EP0fWkp7Pqn289LiXqSXh1Ktzb0bZzymTglEstE0teQ36ZJm0U90qt8PH1rzo+24pqXpAsaIORPFue/IMvmXfg=,iv:TntX6EjTCZrJYXoKs0peUQqZNkssOqB5lGDDsgZXE5s=,tag:gJBc0nYjx22ogRWv+ddL1Q==,type:str]
    pgp:
        - created_at: "2022-11-28T21:59:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ//dRg8o60Uoiu+DZAHvms80qZ+s6wpKPf8gKUSsrB9YiEe
            02vdk6rUV4iZwCLAriVnYk631MfQvmh6PGwXzibL/hGoFNTVojgf889vYHh0aub/
            uyAXzZR4I51ZAOMFnOV5iLIGTkJ8oUrOgNQwGcnXo62gtgncyINh8nuh7ES0eMH1
            l71s8L8qk2klD293gFxrHMB6UFXGSAYqOugH+aVURkqrjO8oYGwWaIkknxD8PJPF
            bF8jPN8iX6VMV4+dRzNKsng76kXFfFm2B0ig2TPFCnUKBa6XCF1PPYIVCrdsbxC/
            Nq9dOC8nedG696VgeK831My8p0h9uiqOVwF5HcariZF4XiCTCyZ/3rY5OdJmBBir
            rvKF77S1Uet1J5ZIHTtvJrsCl5smMqeWGQd09La6f9fMAlKoE5cIuQajAsJrpJeN
            fRydVYsOgTuDkXjGVOQmTCiUaCnNce3gp79MhzLkxDFj6baXiVLhs4jzYFWDXhCj
            C65564fbzSYPQ60lK/fosQduV+wFW/1fwmRnoDIqtUL0U82dO5SNJX2h3ZGe/WN+
            F6fLQRphYWigiVDq5qkvfrVRWK3VyMs+mlM0dOA5m3er20pEXKZNWYGaQwQOzk0P
            54U7hJttQjywrLjFW/ytY6DKOgvpI6CWj/aQvk48lPQQXVN0CqIClH5Z1DlxOmHS
            XAFAs5gY/p/AubD00dAGeemnpoaiuFo0F84zDzqpo+1fC6C45z6VzWYD8gBZq+Wq
            43sXzMmJ3IcnPuRUrfj0dbJrr2ZKMqkVPu0BAcfdnUgrjFEJ9oxnGN/AORuS
            =8z1M
            -----END PGP MESSAGE-----
          fp: C30C5D4937A396E38BC4DCE8FDF7C53BBD031E90
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
